import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";
import Header from "@/components/header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"], 
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} font-roboto antialiased`}>
        <Header />
        <div className="flex flex-row">
          <div className="w-[260px]">
            <SideBar />

          </div>
          <div className="flex flex-col w-[calc(100vw-260px)] mt-10">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
