"use client";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/sidebar";
import Header from "@/components/header";
import { useState } from "react";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [isCollapsed, setIsCollapsed] = useState(true);

  return (
    <html lang="en">
      <body className={`${roboto.variable} font-roboto antialiased`}>
        <Header isCollapsed={isCollapsed} setIsCollapsed={setIsCollapsed} />
        <div className="flex flex-row">
          <div
            className={`${
              isCollapsed ? "w-[60px]" : "w-[260px]"
            } transition-all duration-300`}
          >
            <SideBar
              isCollapsed={isCollapsed}
              setIsCollapsed={setIsCollapsed}
            />
          </div>
          <div
            className={`flex flex-col mt-10 ${
              isCollapsed ? "w-[calc(100vw-60px)]" : "w-[calc(100vw-260px)]"
            }`}
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
